// <auto-generated />
using System;
using BookingWebApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingWebApplication.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240123091122_AddModelsTodb")]
    partial class AddModelsTodb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingWebApplication.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("admins");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("I3D")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("3D")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<int>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("cinemas");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            I3D = "Yes",
                            Name = "Village Cinemas Thessaloniki",
                            Seats = 300
                        },
                        new
                        {
                            Id = 1,
                            I3D = "No",
                            Name = "Options Cinemas Glyfada",
                            Seats = 200
                        },
                        new
                        {
                            Id = 2,
                            I3D = "No",
                            Name = "Άστορ",
                            Seats = 150
                        });
                });

            modelBuilder.Entity("BookingWebApplication.Models.ContentAdmin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("content_admins");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "alex",
                            UserName = "al"
                        });
                });

            modelBuilder.Entity("BookingWebApplication.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("customers");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<string>("MovieName")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_name")
                        .IsFixedLength();

                    b.Property<int>("ContentAdminId")
                        .HasColumnType("int");

                    b.Property<string>("MovieContent")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_content")
                        .IsFixedLength();

                    b.Property<string>("MovieDirector")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_director")
                        .IsFixedLength();

                    b.Property<int>("MovieLength")
                        .HasColumnType("int")
                        .HasColumnName("movie_length");

                    b.Property<string>("MovieSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("movie_summary");

                    b.Property<string>("MovieType")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_type")
                        .IsFixedLength();

                    b.HasKey("MovieId", "MovieName");

                    b.HasIndex("ContentAdminId");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieId = 0,
                            MovieName = "The Shawshank Redemption",
                            ContentAdminId = 0,
                            MovieContent = "Content",
                            MovieDirector = "Frank Darabont",
                            MovieLength = 142,
                            MovieSummary = "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
                            MovieType = "Drama"
                        },
                        new
                        {
                            MovieId = 1,
                            MovieName = "The Godfather",
                            ContentAdminId = 0,
                            MovieContent = "Content",
                            MovieDirector = "Francis Ford Coppola",
                            MovieLength = 175,
                            MovieSummary = "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.",
                            MovieType = "Crime, Drama"
                        },
                        new
                        {
                            MovieId = 2,
                            MovieName = "The Dark Knight",
                            ContentAdminId = 0,
                            MovieContent = "Content",
                            MovieDirector = "Christopher Nolan",
                            MovieLength = 152,
                            MovieSummary = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            MovieType = "Action, Crime, Drama"
                        });
                });

            modelBuilder.Entity("BookingWebApplication.Models.Provoli", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("int")
                        .HasColumnName("MOVIES_ID");

                    b.Property<string>("MoviesName")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("MOVIES_NAME");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CinemasID")
                        .HasColumnType("int");

                    b.Property<int>("ContentAdminId")
                        .HasColumnType("int")
                        .HasColumnName("CONTENT_ADMIN_ID");

                    b.Property<DateTime?>("ShowDateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("ShowDateTime");

                    b.HasKey("MoviesId", "MoviesName", "Id", "CinemasID", "ContentAdminId");

                    b.HasIndex("CinemasID");

                    b.HasIndex("ContentAdminId");

                    b.ToTable("provoles");

                    b.HasData(
                        new
                        {
                            MoviesId = 0,
                            MoviesName = "The Shawshank Redemption",
                            Id = 0,
                            CinemasID = 0,
                            ContentAdminId = 0,
                            ShowDateTime = new DateTime(2024, 1, 28, 11, 11, 21, 997, DateTimeKind.Local).AddTicks(5605)
                        },
                        new
                        {
                            MoviesId = 0,
                            MoviesName = "The Shawshank Redemption",
                            Id = 1,
                            CinemasID = 0,
                            ContentAdminId = 0,
                            ShowDateTime = new DateTime(2024, 1, 29, 18, 11, 21, 997, DateTimeKind.Local).AddTicks(5613)
                        },
                        new
                        {
                            MoviesId = 0,
                            MoviesName = "The Shawshank Redemption",
                            Id = 2,
                            CinemasID = 1,
                            ContentAdminId = 0,
                            ShowDateTime = new DateTime(2024, 1, 27, 18, 11, 21, 997, DateTimeKind.Local).AddTicks(5616)
                        },
                        new
                        {
                            MoviesId = 1,
                            MoviesName = "The Godfather",
                            Id = 3,
                            CinemasID = 2,
                            ContentAdminId = 0,
                            ShowDateTime = new DateTime(2024, 1, 28, 18, 11, 21, 997, DateTimeKind.Local).AddTicks(5619)
                        });
                });

            modelBuilder.Entity("BookingWebApplication.Models.Reservation", b =>
                {
                    b.Property<int>("ProvolesMoviesId")
                        .HasColumnType("int")
                        .HasColumnName("PROVOLES_MOVIES_ID");

                    b.Property<string>("ProvolesMoviesName")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("PROVOLES_MOVIES_NAME");

                    b.Property<int>("ProvolesCinemasId")
                        .HasColumnType("int")
                        .HasColumnName("PROVOLES_CINEMAS_ID");

                    b.Property<int>("ProvolesId")
                        .HasColumnType("int")
                        .HasColumnName("PROVOLES_ID");

                    b.Property<int>("CustomersId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMERS_ID");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int")
                        .HasColumnName("NUMBER_OF_SEATS");

                    b.Property<int>("ProvolesContentAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProvolesDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("PROVOLES_Date_Time");

                    b.Property<string>("Seats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Seats");

                    b.HasKey("ProvolesMoviesId", "ProvolesMoviesName", "ProvolesCinemasId", "ProvolesId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.HasIndex("ProvolesMoviesId", "ProvolesMoviesName", "ProvolesId", "ProvolesCinemasId", "ProvolesContentAdminId");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("BookingWebApplication.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(32)
                        .HasColumnType("nchar(32)")
                        .HasColumnName("user_name")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nchar(35)")
                        .HasColumnName("email")
                        .IsFixedLength();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("password")
                        .IsFixedLength();

                    b.Property<string>("Role")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("role")
                        .IsFixedLength();

                    b.Property<string>("Salt")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("salt")
                        .IsFixedLength();

                    b.HasKey("UserName");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserName = "al",
                            CreateTime = new DateTime(2024, 1, 23, 11, 11, 21, 997, DateTimeKind.Local).AddTicks(5281),
                            Email = "al@testmail.com",
                            Password = "123456",
                            Role = "ContentAdmin",
                            Salt = "123"
                        });
                });

            modelBuilder.Entity("BookingWebApplication.Models.Admin", b =>
                {
                    b.HasOne("BookingWebApplication.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("BookingWebApplication.Models.Admin", "UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingWebApplication.Models.ContentAdmin", b =>
                {
                    b.HasOne("BookingWebApplication.Models.User", "User")
                        .WithOne("ContentAdmin")
                        .HasForeignKey("BookingWebApplication.Models.ContentAdmin", "UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Customer", b =>
                {
                    b.HasOne("BookingWebApplication.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("BookingWebApplication.Models.Customer", "UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Movie", b =>
                {
                    b.HasOne("BookingWebApplication.Models.ContentAdmin", "ContentAdmin")
                        .WithMany("Movies")
                        .HasForeignKey("ContentAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentAdmin");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Provoli", b =>
                {
                    b.HasOne("BookingWebApplication.Models.Cinema", "Cinema")
                        .WithMany("Provoles")
                        .HasForeignKey("CinemasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingWebApplication.Models.ContentAdmin", "ContentAdmin")
                        .WithMany("Provoles")
                        .HasForeignKey("ContentAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingWebApplication.Models.Movie", "Movie")
                        .WithMany("Provoles")
                        .HasForeignKey("MoviesId", "MoviesName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("ContentAdmin");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Reservation", b =>
                {
                    b.HasOne("BookingWebApplication.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingWebApplication.Models.Provoli", "Provoli")
                        .WithMany("Reservations")
                        .HasForeignKey("ProvolesMoviesId", "ProvolesMoviesName", "ProvolesId", "ProvolesCinemasId", "ProvolesContentAdminId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Provoli");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Cinema", b =>
                {
                    b.Navigation("Provoles");
                });

            modelBuilder.Entity("BookingWebApplication.Models.ContentAdmin", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Provoles");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Movie", b =>
                {
                    b.Navigation("Provoles");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Provoli", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BookingWebApplication.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("ContentAdmin");

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
