// <auto-generated />
using System;
using BookingWebApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingWebApplication.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240110123146_AddBasicModelsTodb")]
    partial class AddBasicModelsTodb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingWebApplication.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<int>("UserName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("I3D")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("3D")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("Seats")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("seats")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("cinemas");
                });

            modelBuilder.Entity("BookingWebApplication.Models.ContentAdmin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<int>("UserName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("content_admins");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<int>("UserName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<string>("MovieName")
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_name")
                        .IsFixedLength();

                    b.Property<int>("ContentAdminId")
                        .HasColumnType("int");

                    b.Property<string>("MovieContent")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_description")
                        .IsFixedLength();

                    b.Property<string>("MovieDirector")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_director")
                        .IsFixedLength();

                    b.Property<int>("MovieLength")
                        .HasColumnType("int")
                        .HasColumnName("movie_length");

                    b.Property<string>("MovieSummary")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_summary")
                        .IsFixedLength();

                    b.Property<string>("MovieType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("movie_type")
                        .IsFixedLength();

                    b.HasKey("MovieId", "MovieName");

                    b.HasIndex("ContentAdminId");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Provoli", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CinemasID")
                        .HasColumnType("int");

                    b.Property<int>("ContentAdminId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<string>("MoviesName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("CinemasID");

                    b.HasIndex("ContentAdminId");

                    b.HasIndex("MoviesId", "MoviesName");

                    b.ToTable("provoles");
                });

            modelBuilder.Entity("BookingWebApplication.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(32)
                        .HasColumnType("nchar(32)")
                        .HasColumnName("user_name")
                        .IsFixedLength();

                    b.Property<int?>("AdminUserName")
                        .HasColumnType("int");

                    b.Property<int?>("ContentAdminUserName")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_time");

                    b.Property<int?>("CustomerUserName")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nchar(35)")
                        .HasColumnName("email")
                        .IsFixedLength();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("password")
                        .IsFixedLength();

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("role")
                        .IsFixedLength();

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nchar(45)")
                        .HasColumnName("salt")
                        .IsFixedLength();

                    b.HasKey("UserName");

                    b.HasIndex("AdminUserName")
                        .IsUnique()
                        .HasFilter("[AdminUserName] IS NOT NULL");

                    b.HasIndex("ContentAdminUserName")
                        .IsUnique()
                        .HasFilter("[ContentAdminUserName] IS NOT NULL");

                    b.HasIndex("CustomerUserName")
                        .IsUnique()
                        .HasFilter("[CustomerUserName] IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Movie", b =>
                {
                    b.HasOne("BookingWebApplication.Models.ContentAdmin", "ContentAdmin")
                        .WithMany("Movies")
                        .HasForeignKey("ContentAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentAdmin");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Provoli", b =>
                {
                    b.HasOne("BookingWebApplication.Models.Cinema", "Cinema")
                        .WithMany("Provoles")
                        .HasForeignKey("CinemasID");

                    b.HasOne("BookingWebApplication.Models.ContentAdmin", "ContentAdmin")
                        .WithMany("Provoles")
                        .HasForeignKey("ContentAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingWebApplication.Models.Movie", "Movie")
                        .WithMany("Provoles")
                        .HasForeignKey("MoviesId", "MoviesName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("ContentAdmin");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BookingWebApplication.Models.User", b =>
                {
                    b.HasOne("BookingWebApplication.Models.Admin", "Admin")
                        .WithOne("User")
                        .HasForeignKey("BookingWebApplication.Models.User", "AdminUserName")
                        .HasPrincipalKey("BookingWebApplication.Models.Admin", "UserName");

                    b.HasOne("BookingWebApplication.Models.ContentAdmin", "ContentAdmin")
                        .WithOne("User")
                        .HasForeignKey("BookingWebApplication.Models.User", "ContentAdminUserName")
                        .HasPrincipalKey("BookingWebApplication.Models.ContentAdmin", "UserName");

                    b.HasOne("BookingWebApplication.Models.Customer", "Customer")
                        .WithOne("User")
                        .HasForeignKey("BookingWebApplication.Models.User", "CustomerUserName")
                        .HasPrincipalKey("BookingWebApplication.Models.Customer", "UserName");

                    b.Navigation("Admin");

                    b.Navigation("ContentAdmin");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BookingWebApplication.Models.Admin", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingWebApplication.Models.Cinema", b =>
                {
                    b.Navigation("Provoles");
                });

            modelBuilder.Entity("BookingWebApplication.Models.ContentAdmin", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Provoles");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingWebApplication.Models.Customer", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingWebApplication.Models.Movie", b =>
                {
                    b.Navigation("Provoles");
                });
#pragma warning restore 612, 618
        }
    }
}
